services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: burh-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - burh-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: burh-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - burh-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: burh-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: burh_desafio
      POSTGRES_USER: burh_user
      POSTGRES_PASSWORD: burh_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - burh-network

networks:
  burh-network:
    driver: bridge

volumes:
  db-data:
    driver: local
